# NOTE: This workflow is used to run tests on the back-end directory of the projet
#      when a pull request is made when changes are made to the back-end directory.
name: Back-End Tests

on:
  pull_request:
    paths:
      - "back-end/**" # Run the workflow when changes are made to the back-end directory

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_ama_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Branch Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pip dependencies
        run: |
          cd back-end
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd back-end
          source venv/bin/activate
          pytest **/tests.py
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_ama_db

      - name: Run integration tests
        run: /
          cd back-end
          source venv/bin/activate
          pytest **/test_views.py
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_ama_db
