name: API Tests

on:
  push:
    branches:
      - "**" # This will run the workflow on push events for all branches

    paths:
      - "back-end/**" # This will only run the workflow if files in the 'back-end' directory are changed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Create Virtual Environment
        run: /
          cd back-end
          python -m venv venv

      - name: Install pip dependencies
        run: |
          cd back-end
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
